// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (feed_id, title, link, published_at, created_at, updated_at, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, feed_id, title, link, published_at, created_at, updated_at, url
`

type CreatePostParams struct {
	FeedID      uuid.UUID
	Title       string
	Link        string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Url         string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Url,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
	)
	return i, err
}
