-- +goose Up

CREATE TABLE posts (
	id  UUID PRIMARY KEY,
	feed_id UUID NOT NULL REFERENCES feeds (id) ON DELETE CASCADE,
	title TEXT NOT NULL,
	link TEXT NOT NULL,
	published_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	url TEXT NOT NULL UNIQUE
);

-- +goose Down
DROP TABLE posts;
